project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "research.qmd"
    - "cv.qmd"
    - "contact.qmd"
  resources:
    - CNAME
    - cv/

website:
  title: "Hunter Martaindale"
  description: "Director of Research, ALERRT Center | Texas State University"
  favicon: img/favicon.ico
  navbar:
    background: light
    left:
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "<i class='ai ai-google-scholar' style='font-size:1.1rem;'></i>"
        href: https://scholar.google.com/citations?user=_7PlqKYAAAAJ
        aria-label: Google Scholar
      - text: "<i class='ai ai-orcid' style='font-size:1.1rem;'></i>"
        href: https://orcid.org/0000-0002-8100-7698
        aria-label: ORCID
      - icon: github
        href: https://github.com/huntermartaindale
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/hmartaindale/
        aria-label: LinkedIn
  page-footer:
    center: "Hunter Martaindale | Texas State University"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    link-external-newwindow: true
    link-external-icon: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.6/css/academicons.min.css" integrity="sha512-TNfdJEUUJmfj2DRlAKXBg7HroqoXYLon5XPEEWYa2+H/XSD2HAr0BwkRrAoNLAEz79x7XURTFRWDn9yhMNbbNQ==" crossorigin="anonymous" referrerpolicy="no-referrer">

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
