#!/usr/bin/env Rscript
# scripts/sync_grants.R
#
# Generates data/grants.yaml from the canonical source of truth
# (cv_data.yaml in the huntermartaindale/cv repo). Edit cv_data.yaml,
# not data/grants.yaml.
#
# Filters applied:
#   - status: funded only
#   - excludes PASS (Preparing for Active Shooter Situations) grants by title
#
# Usage:
#   Rscript scripts/sync_grants.R [path/to/cv_data.yaml]
#
# Defaults:
#   - In CI, cv repo is checked out to cv-source/, so default input is
#     cv-source/cv_data.yaml.
#   - Locally from website/, run: Rscript scripts/sync_grants.R ../../cv/cv_data.yaml

suppressPackageStartupMessages({
  library(yaml)
})

`%||%` <- function(a, b) if (!is.null(a)) a else b

drop_empty <- function(lst) {
  keep <- sapply(lst, function(x) {
    !is.null(x) && !(length(x) == 1 && is.atomic(x) && is.na(x))
  })
  lst[keep]
}

args        <- commandArgs(trailingOnly = TRUE)
input_path  <- if (length(args) >= 1) args[1] else "cv-source/cv_data.yaml"
output_path <- "data/grants.yaml"

if (!file.exists(input_path)) {
  stop("CV data file not found: ", input_path)
}

cat("Reading", input_path, "\n")
cv <- yaml::read_yaml(input_path)

if (is.null(cv$grants) || length(cv$grants) == 0) {
  stop("No grants found in ", input_path)
}

# Filter: funded only, exclude PASS recurring grants
is_pass <- function(title) {
  grepl("Preparing for Active Shooter Situations", title %||% "", fixed = TRUE)
}

grants_funded_all <- Filter(function(g) identical(g$status, "funded"), cv$grants)
grants_pass       <- Filter(function(g) is_pass(g$title), grants_funded_all)
grants_funded     <- Filter(function(g) !is_pass(g$title), grants_funded_all)

# Sort by year descending (stable so original order preserved within a year)
years <- sapply(grants_funded, function(g) as.integer(g$year %||% 0))
grants_funded <- grants_funded[order(years, decreasing = TRUE)]

out <- lapply(grants_funded, function(g) {
  drop_empty(list(
    title             = g$title,
    funder            = g$funder,
    role              = g$role,
    pi                = g$pi,
    amount            = g$amount,
    year              = as.integer(g$year),
    prime_pi          = g$prime_pi,
    prime_institution = g$prime_institution,
    prime_total       = g$prime_total,
    notes             = g$notes,
    award_number      = g$award_number
  ))
})

# Header is intentionally free of timestamps / input-path so regeneration is
# deterministic given the same cv_data.yaml. That lets CI commit this file back
# on real content changes only, instead of on every build.
header <- c(
  "# grants.yaml",
  "# AUTO-GENERATED from cv_data.yaml by scripts/sync_grants.R",
  "# Edit cv_data.yaml in huntermartaindale/cv, not this file.",
  "#",
  "# Filters: status == funded; PASS grants excluded.",
  "#",
  paste0("# Total: ", length(out), " grants"),
  ""
)

yaml_str <- yaml::as.yaml(out, indent = 2)
writeLines(c(header, yaml_str), output_path)

# --- summary file --------------------------------------------------------
# Emits totals for funded (non-PASS) and PASS awards so grants.qmd can
# reference both without needing access to cv_data.yaml at render time.

funded_total <- sum(sapply(grants_funded, function(g) as.numeric(g$amount %||% 0)))
pass_total   <- sum(sapply(grants_pass,   function(g) as.numeric(g$amount %||% 0)))

summary_path <- "data/grants_summary.yaml"
summary_data <- list(
  funded_count = length(grants_funded),
  funded_total = funded_total,
  pass_count   = length(grants_pass),
  pass_total   = pass_total
)
writeLines(
  c(
    "# grants_summary.yaml",
    "# AUTO-GENERATED by scripts/sync_grants.R alongside grants.yaml.",
    "# Used by grants.qmd to display summary stats including PASS totals",
    "# (PASS grants are excluded from grants.yaml itself).",
    "",
    yaml::as.yaml(summary_data, indent = 2)
  ),
  summary_path
)

cat(sprintf("\nWrote %d funded grants (PASS excluded) to %s\n", length(out), output_path))
cat(sprintf("  Funded (non-PASS): %d grants, $%s total\n",
            length(grants_funded), formatC(funded_total, format = "d", big.mark = ",")))
cat(sprintf("  PASS (excluded):   %d grants, $%s total\n",
            length(grants_pass), formatC(pass_total, format = "d", big.mark = ",")))
cat(sprintf("Wrote summary stats to %s\n", summary_path))
